apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  initContainers:
  - name: install
    image: debian
    command:
    - /bin/bash
    - -c
    - |
      apt update && apt install -y default-mysql-client-core
      apt install -y curl unzip
      VERSION=$(curl -s https://api.github.com/repos/fullstorydev/grpcurl/releases/latest | grep 'tag_name' | cut -d\" -f4)
      DOWNLOAD_URL="https://github.com/fullstorydev/grpcurl/releases/download/$VERSION/grpcurl_${VERSION:1}_linux_x86_64.tar.gz"
      curl -L $DOWNLOAD_URL -o grpcurl.tar.gz
      tar xvf grpcurl.tar.gz grpcurl
      mv grpcurl /usr/local/bin/
      rm -rf grpcurl.tar.gz
    volumeMounts:
    - name: local-bin
      mountPath: /usr/local/bin
    - name: "bin"
      mountPath: /usr/bin/
  containers:
  - name: app
    image: debian
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
    volumeMounts:
    - name: local-bin
      mountPath: /usr/local/bin
    - name: "bin"
      mountPath: /usr/bin
  volumes:
  - name: local-bin
    emptyDir: {}
  - name: "bin"
    emptyDir: {}